name: metrics
run-name: meow meow meow
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs: 
  animestats:
    runs-on: ubuntu-latest
    steps:
      - name: anime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@latest

            