name: metrics
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs: 
  animestats:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: anime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: ${{ secrets.GH_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters

            