name: metrics
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs: 
  animestats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: anime
        uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/metrics.plugin.anilist.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 4

            