- name: anime
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.anilist.svg
    token: NOT_NEEDED
    base: ""
    plugin_anilist: yes
    plugin_anilist_medias: anime
    plugin_anilist_sections: favorites, watching, characters