name: Waka Readme
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  wakatest:
    name: Update this repo's README
    runs-on: ubuntu-latest

    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
